- name: configure frontend server
  become: yes
  hosts: frontend
  task:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
      
